### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by ktb92677** [vurtun/gui#7]
Hey! I was looking through the OpenGL example and its not entirely clear to me how exactly I change fonts during runtime. Could you show me how to do this?

**Comment by vurtun** [comment]
Hey,
you can change the font in the `gui_config` struct anytime you want even inside a frame. But I don't have a helper function right now. If you want I can add one.

**Comment by vurtun** [comment]
OK I added a helper function called `gui_config_set_font` to the configuration API to change the font over a function call.
