### ISSUE TITLE
Development state issues

### ISSUE THREAD

**Issue by ongamex** [vurtun/gui#8]
Yesterday i wrote a few lines of code to test your library, I've updated the code, and well It no longer compiles.GUI_PANEL_CLOSEABLE GUI_PANEL_MINIMIZABLE were gone. gui_panel_begin had different arguments. 

Is the library in a rapid development stage, or I am doing something wrong?

**Comment by vurtun** [comment]
Hey,
I had a major change in the header API. But it is easy to fix/update. Previously you probably had something like this:
```c
gui_panel_init(&panel, 50, 50, 220, 170,
    GUI_PANEL_BORDER|GUI_PANEL_MOVEABLE|
    GUI_PANEL_CLOSEABLE|GUI_PANEL_SCALEABLE|
    GUI_PANEL_MINIMIZABLE, &buffer, &config);
gui_panel_begin(&layout, &panel, "Title", &input);
```
Now it look like this:
```c
gui_panel_init(&panel, 50, 50, 220, 170,
    GUI_PANEL_BORDER|GUI_PANEL_MOVEABLE|GUI_PANEL_SCALEABLE, &buffer, &config);
gui_panel_begin(&layout, &panel, &input);
gui_panel_header(&layout, "Show", GUI_CLOSEABLE|GUI_MINIMIZABLE, 0);
```
As for the development state, today was probably the last update or major change for a while except for bug fixes.
